import { BoardTemplate } from '../types';

export const BOARD_TEMPLATES: BoardTemplate[] = [
  {
    id: 'sprint-agile',
    name: 'Sprint Planning & Agile Delivery',
    description: 'High-velocity two-week sprint tracker with backlog scoping, active delivery, and QA review stages.',
    icon: 'kanban',
    color: '#3ecf8e',
    category: 'Engineering & Agile',
    groups: [
      { name: 'Sprint Backlog', color: '#6366f1' },
      { name: 'In Active Development', color: '#f59e0b' },
      { name: 'Code Review & QA', color: '#8b5cf6' },
      { name: 'Completed & Deployed', color: '#10b981' },
    ],
    starterItems: [
      {
        title: 'Implement token refresh rotation and rate limiting',
        status: 'Working on it',
        priority: 'urgent',
        due_date: 'Tomorrow, 5:00 PM',
        tags: ['Security', 'Backend'],
        description: 'Ensure expired JWT tokens are refreshed seamlessly with Upstash Redis blacklisting.',
      },
      {
        title: 'Mobile touch gesture tuning for Kanban card drag',
        status: 'In Review',
        priority: 'high',
        due_date: 'Sep 28, 2026',
        tags: ['Mobile', 'UX'],
        description: 'Verify smooth touch interactions without triggering default window scroll.',
      },
      {
        title: 'Unit tests for OCC concurrency token verification',
        status: 'Done',
        priority: 'medium',
        due_date: 'Yesterday',
        tags: ['Testing', 'Quality'],
        description: 'Automated test suite verifying that stale version tokens return HTTP 409 Conflict.',
      },
    ],
  },
  {
    id: 'incident-triage',
    name: 'Bug Triage & Incident Escalation',
    description: 'Production bug tracking with severity tagging, SLA countdowns, and Slack thread bi-directional sync.',
    icon: 'alert-triangle',
    color: '#ef4444',
    category: 'Operations & DevOps',
    groups: [
      { name: 'Incoming Triage', color: '#ef4444' },
      { name: 'Investigation & Root Cause', color: '#f59e0b' },
      { name: 'Fix in Verification', color: '#3b82f6' },
      { name: 'Resolved & Post-Mortem', color: '#10b981' },
    ],
    starterItems: [
      {
        title: 'Investigate 504 gateway timeout on bulk CSV export',
        status: 'Working on it',
        priority: 'urgent',
        due_date: 'Today, 2:00 PM',
        tags: ['Incident', 'Production', 'Database'],
        description: 'Query timeout occurs when workspace contains over 5,000 tasks. Transitioning to streaming cursor.',
      },
      {
        title: 'Add regression tests for Slack webhook challenge response',
        status: 'In Review',
        priority: 'medium',
        due_date: 'Tomorrow',
        tags: ['Slack', 'Webhook'],
        description: 'Verify URL verification handshake returns expected challenge token.',
      },
    ],
  },
  {
    id: 'product-roadmap',
    name: 'Product Roadmap & Quarterly Epics',
    description: 'Strategic milestone planning, cross-functional release targets, and deliverable sequencing.',
    icon: 'layers',
    color: '#3b82f6',
    category: 'Product & Design',
    groups: [
      { name: 'Q3 Objectives & Specs', color: '#3b82f6' },
      { name: 'In Flight Epics', color: '#8b5cf6' },
      { name: 'Launched Milestones', color: '#10b981' },
    ],
    starterItems: [
      {
        title: 'Collaborative real-time presence indicators in board header',
        status: 'Done',
        priority: 'high',
        due_date: 'Sep 25, 2026',
        tags: ['Realtime', 'WebSockets'],
        description: 'Display live multi-user avatar presence stack with online dots and active viewing pills.',
      },
      {
        title: 'AI workspace memory taxonomy generator (/profile, /areas, /people)',
        status: 'Working on it',
        priority: 'high',
        due_date: 'Next week',
        tags: ['AI Memory', 'Taxonomy'],
        description: 'Compile structured markdown context partitions for grounded reasoning.',
      },
    ],
  },
  {
    id: 'customer-support',
    name: 'Customer Support & Escalations',
    description: 'High-touch customer support queue with ticket claiming, response SLAs, and satisfaction audits.',
    icon: 'users',
    color: '#f59e0b',
    category: 'Customer Success',
    groups: [
      { name: 'New Inbound Tickets', color: '#f59e0b' },
      { name: 'Under Investigation', color: '#3b82f6' },
      { name: 'Waiting on Customer Reply', color: '#64748b' },
      { name: 'Ticket Resolved', color: '#10b981' },
    ],
    starterItems: [
      {
        title: 'SSO SAML configuration assistance for enterprise pilot',
        status: 'Working on it',
        priority: 'high',
        due_date: 'Today',
        tags: ['Enterprise', 'SSO'],
        description: 'Customer requested assistance configuring Okta SAML metadata XML.',
      },
      {
        title: 'Clarification regarding CSV bulk export permissions',
        status: 'Done',
        priority: 'low',
        due_date: 'Yesterday',
        tags: ['Billing', 'Export'],
        description: 'Confirmed role requirement: workspace Admin or Owner privileges.',
      },
    ],
  },
  {
    id: 'blank-custom',
    name: 'Blank Custom Board',
    description: 'Clean slate board with standard To Do, In Progress, and Done groups ready for custom customization.',
    icon: 'folder',
    color: '#8b5cf6',
    category: 'General',
    groups: [
      { name: 'To Do', color: '#6366f1' },
      { name: 'In Progress', color: '#f59e0b' },
      { name: 'Done', color: '#10b981' },
    ],
    starterItems: [],
  },
];
