import { UserProfile, Workspace, WorkspaceMember, BoardSummary, MyWorkItem, NotificationItem } from '../types';

export const DEMO_USER: UserProfile = {
  id: 'usr-demo-001',
  email: 'alex.rivera@happytf.dev',
  full_name: 'Alex Rivera',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  job_role: 'Lead Product Architect',
  created_at: '2026-08-15T08:00:00Z',
};

export const INITIAL_WORKSPACES: Workspace[] = [
  {
    id: 'ws-acme-core',
    name: 'Acme Product Lab',
    slug: 'acme-product-lab',
    icon_emoji: '🚀',
    brand_color: '#6366f1',
    created_by: 'usr-demo-001',
    created_at: '2026-08-15T08:00:00Z',
    member_count: 5,
  },
  {
    id: 'ws-design-studio',
    name: 'Horizon Design System',
    slug: 'horizon-design',
    icon_emoji: '🎨',
    brand_color: '#ec4899',
    created_by: 'usr-demo-001',
    created_at: '2026-08-20T10:30:00Z',
    member_count: 3,
  },
  {
    id: 'ws-sprint-ops',
    name: 'Core Infra & SRE',
    slug: 'core-infra-sre',
    icon_emoji: '⚡',
    brand_color: '#10b981',
    created_by: 'usr-demo-001',
    created_at: '2026-09-01T14:15:00Z',
    member_count: 4,
  },
];

export const INITIAL_MEMBERS: Record<string, WorkspaceMember[]> = {
  'ws-acme-core': [
    {
      id: 'wm-01',
      workspace_id: 'ws-acme-core',
      user_id: 'usr-demo-001',
      role: 'owner',
      joined_at: '2026-08-15T08:00:00Z',
      profile: DEMO_USER,
    },
    {
      id: 'wm-02',
      workspace_id: 'ws-acme-core',
      user_id: 'usr-002',
      role: 'admin',
      joined_at: '2026-08-16T09:12:00Z',
      profile: {
        id: 'usr-002',
        email: 'taylor.chen@happytf.dev',
        full_name: 'Taylor Chen',
        avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        job_role: 'Senior Frontend Engineer',
        created_at: '2026-08-16T09:12:00Z',
      },
    },
    {
      id: 'wm-03',
      workspace_id: 'ws-acme-core',
      user_id: 'usr-003',
      role: 'member',
      joined_at: '2026-08-18T14:20:00Z',
      profile: {
        id: 'usr-003',
        email: 'sarah.jenkins@happytf.dev',
        full_name: 'Sarah Jenkins',
        avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
        job_role: 'UX Research Lead',
        created_at: '2026-08-18T14:20:00Z',
      },
    },
    {
      id: 'wm-04',
      workspace_id: 'ws-acme-core',
      user_id: 'usr-004',
      role: 'viewer',
      joined_at: '2026-08-22T11:05:00Z',
      profile: {
        id: 'usr-004',
        email: 'marcus.vance@happytf.dev',
        full_name: 'Marcus Vance',
        avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        job_role: 'VP Product Strategy',
        created_at: '2026-08-22T11:05:00Z',
      },
    },
  ],
};

export const INITIAL_BOARDS: Record<string, BoardSummary[]> = {
  'ws-acme-core': [
    {
      id: 'board-01',
      workspace_id: 'ws-acme-core',
      name: 'Q3 Product Roadmap & Deliverables',
      icon_emoji: '🎯',
      description: 'Strategic milestones, sprint commitments, and feature deliveries for Q3.',
      item_count: 28,
      updated_at: '10 mins ago',
      member_avatars: [
        'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
      ],
    },
    {
      id: 'board-02',
      workspace_id: 'ws-acme-core',
      name: 'Sprint 24 — Realtime Engine',
      icon_emoji: '⚡',
      description: 'Two-week sprint tracking live Supabase sync, optimistic UI updates, and conflict handling.',
      item_count: 14,
      updated_at: '1 hour ago',
      member_avatars: [
        'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
      ],
    },
    {
      id: 'board-03',
      workspace_id: 'ws-acme-core',
      name: 'Enterprise Client Pipeline',
      icon_emoji: '💼',
      description: 'High-value customer onboarding, pilot accounts, and enterprise SLA tracking.',
      item_count: 19,
      updated_at: '3 hours ago',
      member_avatars: [
        'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
      ],
    },
  ],
};

export const INITIAL_MY_WORK_ITEMS: MyWorkItem[] = [
  {
    id: 'task-101',
    board_id: 'board-02',
    board_name: 'Sprint 24 — Realtime Engine',
    workspace_id: 'ws-acme-core',
    title: 'Configure Supabase RLS policies for multi-tenant workspace isolation',
    status: 'Working on it',
    status_color: '#f59e0b',
    priority: 'urgent',
    due_date: 'Today, 5:00 PM',
    assignee_id: 'usr-demo-001',
    is_overdue: false,
  },
  {
    id: 'task-102',
    board_id: 'board-01',
    board_name: 'Q3 Product Roadmap',
    workspace_id: 'ws-acme-core',
    title: 'Finalize UX specifications for 3-step onboarding wizard',
    status: 'In Review',
    status_color: '#8b5cf6',
    priority: 'high',
    due_date: 'Tomorrow',
    assignee_id: 'usr-demo-001',
    is_overdue: false,
  },
  {
    id: 'task-103',
    board_id: 'board-02',
    board_name: 'Sprint 24 — Realtime Engine',
    workspace_id: 'ws-acme-core',
    title: 'Design keyboard shortcut palette (⌘K) with fuzzy board search',
    status: 'Done',
    status_color: '#10b981',
    priority: 'medium',
    due_date: 'Yesterday',
    assignee_id: 'usr-demo-001',
    is_overdue: false,
  },
  {
    id: 'task-104',
    board_id: 'board-03',
    board_name: 'Enterprise Client Pipeline',
    workspace_id: 'ws-acme-core',
    title: 'Prepare compliance export audit log format for FinTech beta clients',
    status: 'Pending',
    status_color: '#6b7280',
    priority: 'low',
    due_date: 'Sep 15, 2026',
    assignee_id: 'usr-demo-001',
    is_overdue: false,
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-01',
    title: 'Taylor Chen mentioned you',
    description: 'in "Sprint 24 — Realtime Engine": "Take a look at the websocket channel schema"',
    timestamp: '12m ago',
    unread: true,
    type: 'mention',
  },
  {
    id: 'notif-02',
    title: 'Assigned to new task',
    description: 'You were assigned to "Configure Supabase RLS policies for multi-tenant isolation"',
    timestamp: '45m ago',
    unread: true,
    type: 'assignment',
  },
  {
    id: 'notif-03',
    title: 'Workspace Invite Accepted',
    description: 'Sarah Jenkins accepted your invitation to join Acme Product Lab',
    timestamp: '2h ago',
    unread: false,
    type: 'invite',
  },
  {
    id: 'notif-04',
    title: 'Security Notice',
    description: 'New session authenticated from Chrome 134 on Windows 11',
    timestamp: '1d ago',
    unread: false,
    type: 'system',
  },
];
