import { 
  UserProfile, 
  Workspace, 
  WorkspaceMember, 
  BoardSummary, 
  MyWorkItem, 
  NotificationItem,
  BoardGroup,
  BoardItem
} from '../types';

export const DEMO_USER: UserProfile = {
  id: 'usr-demo-001',
  email: 'alex.rivera@happytf.dev',
  full_name: 'Alex Rivera',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  job_role: 'Lead Product Architect',
  created_at: '2026-08-15T08:00:00Z',
};

export const INITIAL_WORKSPACES: Workspace[] = [
  {
    id: 'ws-acme-core',
    name: 'Acme Product Lab',
    slug: 'acme-product-lab',
    icon_emoji: '🚀',
    brand_color: '#6366f1',
    created_by: 'usr-demo-001',
    created_at: '2026-08-15T08:00:00Z',
    member_count: 4,
  },
  {
    id: 'ws-design-studio',
    name: 'Horizon Design System',
    slug: 'horizon-design',
    icon_emoji: '🎨',
    brand_color: '#ec4899',
    created_by: 'usr-demo-001',
    created_at: '2026-08-20T10:30:00Z',
    member_count: 3,
  },
  {
    id: 'ws-sprint-ops',
    name: 'Core Infra & SRE',
    slug: 'core-infra-sre',
    icon_emoji: '⚡',
    brand_color: '#10b981',
    created_by: 'usr-demo-001',
    created_at: '2026-09-01T14:15:00Z',
    member_count: 4,
  },
];

export const INITIAL_MEMBERS: Record<string, WorkspaceMember[]> = {
  'ws-acme-core': [
    {
      id: 'wm-01',
      workspace_id: 'ws-acme-core',
      user_id: 'usr-demo-001',
      role: 'owner',
      joined_at: '2026-08-15T08:00:00Z',
      profile: DEMO_USER,
    },
    {
      id: 'wm-02',
      workspace_id: 'ws-acme-core',
      user_id: 'usr-002',
      role: 'admin',
      joined_at: '2026-08-16T09:12:00Z',
      profile: {
        id: 'usr-002',
        email: 'taylor.chen@happytf.dev',
        full_name: 'Taylor Chen',
        avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        job_role: 'Senior Frontend Engineer',
        created_at: '2026-08-16T09:12:00Z',
      },
    },
    {
      id: 'wm-03',
      workspace_id: 'ws-acme-core',
      user_id: 'usr-003',
      role: 'member',
      joined_at: '2026-08-18T14:20:00Z',
      profile: {
        id: 'usr-003',
        email: 'sarah.jenkins@happytf.dev',
        full_name: 'Sarah Jenkins',
        avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
        job_role: 'UX Research Lead',
        created_at: '2026-08-18T14:20:00Z',
      },
    },
    {
      id: 'wm-04',
      workspace_id: 'ws-acme-core',
      user_id: 'usr-004',
      role: 'viewer',
      joined_at: '2026-08-22T11:05:00Z',
      profile: {
        id: 'usr-004',
        email: 'marcus.vance@happytf.dev',
        full_name: 'Marcus Vance',
        avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        job_role: 'VP Product Strategy',
        created_at: '2026-08-22T11:05:00Z',
      },
    },
  ],
};

export const INITIAL_BOARDS: Record<string, BoardSummary[]> = {
  'ws-acme-core': [
    {
      id: 'board-01',
      workspace_id: 'ws-acme-core',
      name: 'Q3 Product Roadmap & Deliverables',
      icon_emoji: '🎯',
      description: 'Strategic milestones, sprint commitments, and feature deliveries for Q3.',
      item_count: 6,
      updated_at: '10 mins ago',
      member_avatars: [
        'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
      ],
    },
    {
      id: 'board-02',
      workspace_id: 'ws-acme-core',
      name: 'Sprint 24 — Realtime Engine',
      icon_emoji: '⚡',
      description: 'Two-week sprint tracking live Supabase sync, optimistic UI updates, and conflict handling.',
      item_count: 5,
      updated_at: '1 hour ago',
      member_avatars: [
        'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
      ],
    },
    {
      id: 'board-03',
      workspace_id: 'ws-acme-core',
      name: 'Enterprise Client Pipeline',
      icon_emoji: '💼',
      description: 'High-value customer onboarding, pilot accounts, and enterprise SLA tracking.',
      item_count: 4,
      updated_at: '3 hours ago',
      member_avatars: [
        'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
      ],
    },
  ],
};

export const INITIAL_BOARD_GROUPS: Record<string, BoardGroup[]> = {
  'board-01': [
    { id: 'grp-01-todo', board_id: 'board-01', name: 'Backlog & Scoping', color: '#6366f1' },
    { id: 'grp-01-progress', board_id: 'board-01', name: 'In Development', color: '#f59e0b' },
    { id: 'grp-01-done', board_id: 'board-01', name: 'Shipped & Verified', color: '#10b981' },
  ],
  'board-02': [
    { id: 'grp-02-todo', board_id: 'board-02', name: 'Sprint Backlog', color: '#6366f1' },
    { id: 'grp-02-progress', board_id: 'board-02', name: 'Active Sprint', color: '#f59e0b' },
    { id: 'grp-02-done', board_id: 'board-02', name: 'Ready for Review', color: '#10b981' },
  ],
  'board-03': [
    { id: 'grp-03-todo', board_id: 'board-03', name: 'Lead Qualification', color: '#6366f1' },
    { id: 'grp-03-progress', board_id: 'board-03', name: 'Security Review & POC', color: '#f59e0b' },
    { id: 'grp-03-done', board_id: 'board-03', name: 'Contract Signed', color: '#10b981' },
  ],
};

export const INITIAL_BOARD_ITEMS: Record<string, BoardItem[]> = {
  'board-01': [
    {
      id: 'item-01-1',
      board_id: 'board-01',
      group_id: 'grp-01-progress',
      title: 'Finalize UX specifications for 3-step onboarding wizard',
      status: 'In Review',
      status_color: '#8b5cf6',
      priority: 'high',
      due_date: 'Tomorrow',
      assignee: {
        id: 'usr-demo-001',
        name: 'Alex Rivera',
        avatar: DEMO_USER.avatar_url!,
      },
      tags: ['UX Design', 'Specs', 'Growth'],
      description: 'Document user flows, drop-off mitigation mechanisms, and celebratory confetti triggers for the new team onboarding funnel.',
      activities: [
        { id: 'act-1', author_name: 'Alex Rivera', action: 'Created task and drafted wireframes', timestamp: 'Yesterday, 4:15 PM' },
        { id: 'act-2', author_name: 'Sarah Jenkins', action: 'Reviewed interaction copy and step validation', timestamp: '2 hours ago' },
      ],
      comments: [
        {
          id: 'comm-1',
          author_name: 'Sarah Jenkins',
          author_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
          content: 'The 3-step progressive profiling is huge for decreasing signup bounce. Ensure the bulk invite step remains optional!',
          timestamp: '3 hours ago',
          reactions: [{ emoji: '👍', count: 3, users: ['Alex Rivera', 'Taylor Chen', 'Marcus Vance'] }],
        },
      ],
    },
    {
      id: 'item-01-2',
      board_id: 'board-01',
      group_id: 'grp-01-todo',
      title: 'Design token architecture for multi-theme support (Dark & Light)',
      status: 'Working on it',
      status_color: '#f59e0b',
      priority: 'urgent',
      due_date: 'Sep 12, 2026',
      assignee: {
        id: 'usr-002',
        name: 'Taylor Chen',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      },
      tags: ['Design System', 'CSS Variables', 'Tokens'],
      description: 'Establish 3-tier CSS variables architecture ensuring WCAG 2.2 AA compliance across dark canvas and light modes.',
      activities: [
        { id: 'act-3', author_name: 'Taylor Chen', action: 'Drafted color tokens in globals.css', timestamp: '5 hours ago' },
      ],
      comments: [],
    },
    {
      id: 'item-01-3',
      board_id: 'board-01',
      group_id: 'grp-01-done',
      title: 'Architect PostgreSQL RLS policies for multi-tenant workspace isolation',
      status: 'Done',
      status_color: '#10b981',
      priority: 'urgent',
      due_date: 'Sep 05, 2026',
      assignee: {
        id: 'usr-demo-001',
        name: 'Alex Rivera',
        avatar: DEMO_USER.avatar_url!,
      },
      tags: ['Backend', 'Security', 'Postgres'],
      description: 'Implemented row-level security for workspaces, members, and invites with automated user creation triggers.',
      activities: [
        { id: 'act-4', author_name: 'Alex Rivera', action: 'Committed migration 20260908000001_month1_foundation.sql', timestamp: 'Sep 05' },
      ],
      comments: [
        {
          id: 'comm-2',
          author_name: 'Marcus Vance',
          author_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
          content: 'Passed security audit for enterprise compliance. Great work!',
          timestamp: 'Sep 06',
          reactions: [{ emoji: '🚀', count: 4, users: ['Alex Rivera', 'Taylor Chen', 'Sarah Jenkins', 'Marcus Vance'] }],
        },
      ],
    },
    {
      id: 'item-01-4',
      board_id: 'board-01',
      group_id: 'grp-01-todo',
      title: 'Kanban view drag-and-drop state persistence',
      status: 'Pending',
      status_color: '#64748b',
      priority: 'medium',
      due_date: 'Sep 18, 2026',
      assignee: {
        id: 'usr-002',
        name: 'Taylor Chen',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      },
      tags: ['Frontend', 'Kanban', 'Views'],
      description: 'Smooth card dragging between status columns with optimistic updates and rollback on network drop.',
      activities: [],
      comments: [],
    },
    {
      id: 'item-01-5',
      board_id: 'board-01',
      group_id: 'grp-01-progress',
      title: 'Keyboard shortcut navigation system (? cheat sheet & roving tabindex)',
      status: 'Working on it',
      status_color: '#f59e0b',
      priority: 'high',
      due_date: 'Sep 14, 2026',
      assignee: {
        id: 'usr-demo-001',
        name: 'Alex Rivera',
        avatar: DEMO_USER.avatar_url!,
      },
      tags: ['Accessibility', 'UX', 'Keyboard'],
      description: 'Support arrow key navigation, ? for shortcut map, and rapid cell editing shortcuts.',
      activities: [],
      comments: [],
    },
    {
      id: 'item-01-6',
      board_id: 'board-01',
      group_id: 'grp-01-done',
      title: 'Unified App Shell with collapsible sidebar and ⌘K Command Palette',
      status: 'Done',
      status_color: '#10b981',
      priority: 'urgent',
      due_date: 'Sep 07, 2026',
      assignee: {
        id: 'usr-demo-001',
        name: 'Alex Rivera',
        avatar: DEMO_USER.avatar_url!,
      },
      tags: ['Navigation', 'Shell', 'CommandPalette'],
      description: 'Fast responsive shell with fuzzy search across boards, workspaces, and actions.',
      activities: [],
      comments: [],
    },
  ],
  'board-02': [
    {
      id: 'item-02-1',
      board_id: 'board-02',
      group_id: 'grp-02-progress',
      title: 'Live WebSocket subscription channel for cell update broadcasts',
      status: 'Working on it',
      status_color: '#f59e0b',
      priority: 'urgent',
      due_date: 'Today, 5:00 PM',
      assignee: {
        id: 'usr-demo-001',
        name: 'Alex Rivera',
        avatar: DEMO_USER.avatar_url!,
      },
      tags: ['WebSockets', 'Realtime', 'Supabase'],
      description: 'Broadcast cell-level diffs with user presence indicators to prevent collision overwrites.',
      activities: [],
      comments: [],
    },
    {
      id: 'item-02-2',
      board_id: 'board-02',
      group_id: 'grp-02-todo',
      title: 'Non-intrusive cell locking banner (Alex is editing...)',
      status: 'Pending',
      status_color: '#64748b',
      priority: 'medium',
      due_date: 'Sep 20, 2026',
      assignee: {
        id: 'usr-002',
        name: 'Taylor Chen',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      },
      tags: ['Collaboration', 'UI', 'Locking'],
      description: 'Display 1.5px colored border in editor avatar color to avoid concurrent write confusion.',
      activities: [],
      comments: [],
    },
  ],
};

export const INITIAL_MY_WORK_ITEMS: MyWorkItem[] = [
  {
    id: 'item-01-1',
    board_id: 'board-01',
    board_name: 'Q3 Product Roadmap',
    workspace_id: 'ws-acme-core',
    title: 'Finalize UX specifications for 3-step onboarding wizard',
    status: 'In Review',
    status_color: '#8b5cf6',
    priority: 'high',
    due_date: 'Tomorrow',
    assignee_id: 'usr-demo-001',
    is_overdue: false,
  },
  {
    id: 'item-02-1',
    board_id: 'board-02',
    board_name: 'Sprint 24 — Realtime Engine',
    workspace_id: 'ws-acme-core',
    title: 'Configure Supabase RLS policies for multi-tenant workspace isolation',
    status: 'Working on it',
    status_color: '#f59e0b',
    priority: 'urgent',
    due_date: 'Today, 5:00 PM',
    assignee_id: 'usr-demo-001',
    is_overdue: false,
  },
  {
    id: 'item-01-5',
    board_id: 'board-01',
    board_name: 'Q3 Product Roadmap',
    workspace_id: 'ws-acme-core',
    title: 'Design keyboard shortcut palette (⌘K) with fuzzy board search',
    status: 'Done',
    status_color: '#10b981',
    priority: 'medium',
    due_date: 'Yesterday',
    assignee_id: 'usr-demo-001',
    is_overdue: false,
  },
  {
    id: 'item-01-2',
    board_id: 'board-01',
    board_name: 'Q3 Product Roadmap',
    workspace_id: 'ws-acme-core',
    title: 'Design token architecture for multi-theme support (Dark & Light)',
    status: 'Working on it',
    status_color: '#f59e0b',
    priority: 'urgent',
    due_date: 'Sep 12, 2026',
    assignee_id: 'usr-demo-001',
    is_overdue: false,
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-01',
    title: 'Taylor Chen mentioned you',
    description: 'in "Sprint 24 — Realtime Engine": "Take a look at the websocket channel schema"',
    timestamp: '12m ago',
    unread: true,
    type: 'mention',
  },
  {
    id: 'notif-02',
    title: 'Assigned to new task',
    description: 'You were assigned to "Configure Supabase RLS policies for multi-tenant isolation"',
    timestamp: '45m ago',
    unread: true,
    type: 'assignment',
  },
  {
    id: 'notif-03',
    title: 'Workspace Invite Accepted',
    description: 'Sarah Jenkins accepted your invitation to join Acme Product Lab',
    timestamp: '2h ago',
    unread: false,
    type: 'invite',
  },
  {
    id: 'notif-04',
    title: 'Security Notice',
    description: 'New session authenticated from Chrome 134 on Windows 11',
    timestamp: '1d ago',
    unread: false,
    type: 'system',
  },
];
