import { 
  UserProfile, 
  Workspace, 
  WorkspaceMember, 
  BoardSummary, 
  MyWorkItem, 
  NotificationItem,
  BoardGroup,
  BoardItem,
  GitHubCommit,
  Folder,
  BoardColumn,
  SubItem
} from '../types';

export const DEFAULT_BOARD_COLUMNS: BoardColumn[] = [
  { id: 'col-item', title: 'Item', type: 'text', width: 340 },
  { id: 'col-status', title: 'Status', type: 'status', width: 140 },
  { id: 'col-person', title: 'Owner', type: 'people', width: 130 },
  { id: 'col-priority', title: 'Priority', type: 'priority', width: 120 },
  { id: 'col-date', title: 'Due Date', type: 'date', width: 120 },
  { id: 'col-numbers', title: 'Story Pts', type: 'numbers', width: 100, settings: { unit: 'pts' } },
  { id: 'col-formula', title: 'Calculated SLA', type: 'formula', width: 130, settings: { formula: '{Story Pts} * 1.5' } },
  { id: 'col-subitems', title: 'Sub-Items', type: 'subitems', width: 130 },
];

export const INITIAL_FOLDERS: Record<string, Folder[]> = {
  'ws-acme-core': [
    {
      id: 'fld-ops',
      workspace_id: 'ws-acme-core',
      name: 'Customer & Operations',
      color: '#6366f1',
      collapsed: false,
    },
    {
      id: 'fld-sprints',
      workspace_id: 'ws-acme-core',
      name: 'Engineering & Sprints',
      color: '#3ecf8e',
      collapsed: false,
    },
  ],
  'ws-design-studio': [],
  'ws-sprint-ops': [],
};

export const DEMO_USER: UserProfile = {
  id: 'usr-demo-001',
  email: 'alex.rivera@happytf.dev',
  full_name: 'Alex Rivera',
  avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&auto=format&fit=crop&crop=faces&q=85',
  job_role: 'Lead Product Architect',
  created_at: '2026-08-15T08:00:00Z',
};

export const INITIAL_WORKSPACES: Workspace[] = [
  {
    id: 'ws-acme-core',
    name: 'Acme Product Lab',
    slug: 'acme-product-lab',
    icon_emoji: 'rocket',
    brand_color: '#3ecf8e',
    created_by: 'usr-demo-001',
    created_at: '2026-08-15T08:00:00Z',
    member_count: 4,
  },
  {
    id: 'ws-design-studio',
    name: 'Horizon Design System',
    slug: 'horizon-design',
    icon_emoji: 'palette',
    brand_color: '#ec4899',
    created_by: 'usr-demo-001',
    created_at: '2026-08-20T10:30:00Z',
    member_count: 3,
  },
  {
    id: 'ws-sprint-ops',
    name: 'Core Infra & SRE',
    slug: 'core-infra-sre',
    icon_emoji: 'zap',
    brand_color: '#10b981',
    created_by: 'usr-demo-001',
    created_at: '2026-09-01T14:15:00Z',
    member_count: 4,
  },
];

export const INITIAL_MEMBERS: Record<string, WorkspaceMember[]> = {
  'ws-acme-core': [
    {
      id: 'wm-01',
      workspace_id: 'ws-acme-core',
      user_id: 'usr-demo-001',
      role: 'owner',
      joined_at: '2026-08-15T08:00:00Z',
      profile: DEMO_USER,
    },
    {
      id: 'wm-02',
      workspace_id: 'ws-acme-core',
      user_id: 'usr-002',
      role: 'admin',
      joined_at: '2026-08-16T09:12:00Z',
      profile: {
        id: 'usr-002',
        email: 'taylor.chen@happytf.dev',
        full_name: 'Taylor Chen',
        avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        job_role: 'Senior Frontend Engineer',
        created_at: '2026-08-16T09:12:00Z',
      },
    },
    {
      id: 'wm-03',
      workspace_id: 'ws-acme-core',
      user_id: 'usr-003',
      role: 'member',
      joined_at: '2026-08-18T14:20:00Z',
      profile: {
        id: 'usr-003',
        email: 'sarah.jenkins@happytf.dev',
        full_name: 'Sarah Jenkins',
        avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
        job_role: 'UX Research Lead',
        created_at: '2026-08-18T14:20:00Z',
      },
    },
    {
      id: 'wm-04',
      workspace_id: 'ws-acme-core',
      user_id: 'usr-004',
      role: 'viewer',
      joined_at: '2026-08-22T11:05:00Z',
      profile: {
        id: 'usr-004',
        email: 'marcus.vance@happytf.dev',
        full_name: 'Marcus Vance',
        avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        job_role: 'VP Product Strategy',
        created_at: '2026-08-22T11:05:00Z',
      },
    },
  ],
};

export const INITIAL_BOARDS: Record<string, BoardSummary[]> = {
  'ws-acme-core': [
    {
      id: 'board-tickets',
      workspace_id: 'ws-acme-core',
      folder_id: 'fld-ops',
      name: 'Incident Response & Ticket Triage',
      icon_emoji: 'alert-triangle',
      description: 'Production bug triage, Slack alerts, customer escalation workflows, and live SLAs.',
      item_count: 4,
      updated_at: 'Just now',
      member_avatars: [
        'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
      ],
      columns: [...DEFAULT_BOARD_COLUMNS],
    },
    {
      id: 'board-01',
      workspace_id: 'ws-acme-core',
      name: 'Q3 Product Roadmap & Deliverables',
      icon_emoji: 'target',
      description: 'Strategic milestones, sprint commitments, and feature deliveries for Q3.',
      item_count: 6,
      updated_at: '10 mins ago',
      member_avatars: [
        'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
      ],
      columns: [...DEFAULT_BOARD_COLUMNS],
    },

    {
      id: 'board-02',
      workspace_id: 'ws-acme-core',
      folder_id: 'fld-sprints',
      name: 'Sprint 24 — Realtime Engine',
      icon_emoji: 'zap',
      description: 'Two-week sprint tracking live Supabase sync, optimistic UI updates, and conflict handling.',
      item_count: 5,
      updated_at: '1 hour ago',
      member_avatars: [
        'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
      ],
      columns: [...DEFAULT_BOARD_COLUMNS],
    },
    {
      id: 'board-03',
      workspace_id: 'ws-acme-core',
      name: 'Enterprise Client Pipeline',
      icon_emoji: 'briefcase',
      description: 'High-value customer onboarding, pilot accounts, and enterprise SLA tracking.',
      item_count: 4,
      updated_at: '3 hours ago',
      member_avatars: [
        'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
      ],
      columns: [...DEFAULT_BOARD_COLUMNS],
    },
  ],
};

export function getDefaultBoardGroups(boardId: string): BoardGroup[] {
  return [
    { id: `grp-${boardId}-todo`, board_id: boardId, name: 'To Do', color: '#6366f1', collapsed: false },
    { id: `grp-${boardId}-progress`, board_id: boardId, name: 'In Progress', color: '#f59e0b', collapsed: false },
    { id: `grp-${boardId}-done`, board_id: boardId, name: 'Done', color: '#10b981', collapsed: false },
  ];
}

export const INITIAL_BOARD_GROUPS: Record<string, BoardGroup[]> = {
  'board-tickets': [
    { id: 'grp-tk-triage', board_id: 'board-tickets', name: 'Triage & Inbound', color: '#ec4899' },
    { id: 'grp-tk-progress', board_id: 'board-tickets', name: 'Active Investigation & Fix', color: '#f59e0b' },
    { id: 'grp-tk-review', board_id: 'board-tickets', name: 'PR Review & QA', color: '#8b5cf6' },
    { id: 'grp-tk-done', board_id: 'board-tickets', name: 'Resolved & Closed', color: '#10b981' },
  ],
  'board-01': [
    { id: 'grp-01-todo', board_id: 'board-01', name: 'Backlog & Scoping', color: '#6366f1' },
    { id: 'grp-01-progress', board_id: 'board-01', name: 'In Development', color: '#f59e0b' },
    { id: 'grp-01-done', board_id: 'board-01', name: 'Shipped & Verified', color: '#10b981' },
  ],
  'board-02': [
    { id: 'grp-02-todo', board_id: 'board-02', name: 'Sprint Backlog', color: '#6366f1' },
    { id: 'grp-02-progress', board_id: 'board-02', name: 'Active Sprint', color: '#f59e0b' },
    { id: 'grp-02-done', board_id: 'board-02', name: 'Ready for Review', color: '#10b981' },
  ],
  'board-03': [
    { id: 'grp-03-todo', board_id: 'board-03', name: 'Lead Qualification', color: '#6366f1' },
    { id: 'grp-03-progress', board_id: 'board-03', name: 'Security Review & POC', color: '#f59e0b' },
    { id: 'grp-03-done', board_id: 'board-03', name: 'Contract Signed', color: '#10b981' },
  ],
};

export const INITIAL_BOARD_ITEMS: Record<string, BoardItem[]> = {
  'board-tickets': [
    {
      id: 'item-tk-1',
      ticket_number: 'TK-1042',
      board_id: 'board-tickets',
      group_id: 'grp-tk-progress',
      title: 'Fix 504 Gateway Timeout on bulk ticket export via background worker',
      status: 'Working on it',
      status_color: '#f59e0b',
      priority: 'urgent',
      severity: 'critical',
      start_date: new Date().toISOString().split('T')[0],
      due_date: new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0],
      blocked_by: [],
      blocks: ['item-tk-2'],
      sla_due_at: new Date(Date.now() + 2.5 * 3600 * 1000).toISOString(),
      external_source: 'slack',
      slack_channel_id: '#eng-prod-alerts',
      assignee: {
        id: 'usr-demo-001',
        name: 'Alex Rivera',
        avatar: DEMO_USER.avatar_url!,
      },
      tags: ['Production', 'Postgres', 'Hotfix'],
      numbers_value: 10,
      sub_items: [
        {
          id: 'sub-1',
          parent_id: 'item-tk-1',
          title: 'Reproduce timeout with 10k rows on staging',
          status: 'Done',
          status_color: '#10b981',
          assignee: { id: 'usr-demo-001', name: 'Alex Rivera', avatar: DEMO_USER.avatar_url! },
          due_date: 'Today',
          number_val: 3,
          completed: true,
        },
        {
          id: 'sub-2',
          parent_id: 'item-tk-1',
          title: 'Stream CSV response with chunked transfer',
          status: 'Done',
          status_color: '#10b981',
          assignee: { id: 'usr-002', name: 'Taylor Chen', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150' },
          due_date: 'Today',
          number_val: 5,
          completed: true,
        },
        {
          id: 'sub-3',
          parent_id: 'item-tk-1',
          title: 'Deploy hotfix to edge proxy and verify latency',
          status: 'Working on it',
          status_color: '#f59e0b',
          assignee: { id: 'usr-demo-001', name: 'Alex Rivera', avatar: DEMO_USER.avatar_url! },
          due_date: 'Tomorrow',
          number_val: 2,
          completed: false,
        },
      ],
      subtasks: [
        { id: 'st-1', title: 'Reproduce timeout with 10k rows', completed: true },
        { id: 'st-2', title: 'Stream CSV with chunked response', completed: true },
        { id: 'st-3', title: 'Deploy hotfix to edge proxy', completed: false },
      ],
      description: 'Customer data export hangs on workspace with >10,000 tickets. Investigating DB connection pool starvation in Next.js route handler.',
      activities: [
        { id: 'act-tk-1', author_name: 'Slack Bot', action: 'Created from #eng-prod-alerts via /ticket command', timestamp: '35 mins ago' },
        { id: 'act-tk-2', author_name: 'Alex Rivera', action: 'Claimed ticket from Slack', timestamp: '20 mins ago' },
      ],
      comments: [
        {
          id: 'comm-tk-1',
          author_name: 'Taylor Chen',
          author_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
          content: 'Upstash Redis queue can offload this asynchronously with BullMQ worker.',
          timestamp: '15 mins ago',
          reactions: [{ emoji: '🔥', count: 2, users: ['Alex Rivera', 'Taylor Chen'] }],
        },
      ],
      version: 2,
    },
    {
      id: 'item-tk-2',
      ticket_number: 'TK-1043',
      board_id: 'board-tickets',
      group_id: 'grp-tk-review',
      title: 'Slack thread comments not syncing into closed tickets',
      status: 'In Review',
      status_color: '#8b5cf6',
      priority: 'high',
      severity: 'major',
      start_date: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
      due_date: new Date(Date.now() + 5 * 86400000).toISOString().split('T')[0],
      blocked_by: ['item-tk-1'],
      blocks: ['item-tk-3'],
      sla_due_at: new Date(Date.now() + 18 * 3600 * 1000).toISOString(),
      external_source: 'slack',
      slack_channel_id: '#integrations',
      assignee: {
        id: 'usr-002',
        name: 'Taylor Chen',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      },
      tags: ['Integrations', 'Slack API'],
      subtasks: [
        { id: 'st-4', title: 'Update Slack event filter for resolved status', completed: true },
        { id: 'st-5', title: 'Add regression unit test', completed: true },
      ],
      description: 'Webhook router dropped app_mention events when ticket had status `done`. Added status bypass logic.',
      activities: [
        { id: 'act-tk-3', author_name: 'Taylor Chen', action: 'Submitted PR #42 for review', timestamp: '1 hour ago' },
      ],
      comments: [],
      version: 3,
    },
    {
      id: 'item-tk-3',
      ticket_number: 'TK-1044',
      board_id: 'board-tickets',
      group_id: 'grp-tk-triage',
      title: 'Add Monday.com column mapping presets for Customer Success board',
      status: 'Working on it',
      status_color: '#f59e0b',
      priority: 'medium',
      severity: 'minor',
      start_date: new Date(Date.now() + 6 * 86400000).toISOString().split('T')[0],
      due_date: new Date(Date.now() + 8 * 86400000).toISOString().split('T')[0],
      blocked_by: ['item-tk-2'],
      blocks: [],
      sla_due_at: new Date(Date.now() + 48 * 3600 * 1000).toISOString(),
      external_source: 'monday',
      assignee: {
        id: 'usr-003',
        name: 'Sarah Jenkins',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
      },
      tags: ['Monday.com', 'CS Ops'],
      subtasks: [],
      description: 'Enable mapping between Monday.com custom dropdowns and HappyTF SLA priority tags.',
      activities: [],
      comments: [],
      version: 1,
    },
    {
      id: 'item-tk-4',
      ticket_number: 'TK-1045',
      board_id: 'board-tickets',
      group_id: 'grp-tk-done',
      title: 'Security patch: Rotate Redis session tokens on privilege downgrade',
      status: 'Done',
      status_color: '#10b981',
      priority: 'urgent',
      severity: 'critical',
      start_date: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
      due_date: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
      blocked_by: [],
      blocks: [],
      sla_due_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
      external_source: 'web',
      assignee: {
        id: 'usr-demo-001',
        name: 'Alex Rivera',
        avatar: DEMO_USER.avatar_url!,
      },
      tags: ['Security', 'Auth', 'Redis'],
      subtasks: [
        { id: 'st-6', title: 'Invalidate old tokens in Redis', completed: true },
        { id: 'st-7', title: 'Audit logs verification', completed: true },
      ],
      description: 'When a member role changes from Admin to Member or Viewer, immediately purge cached bearer tokens from Upstash Redis.',
      activities: [
        { id: 'act-tk-4', author_name: 'Alex Rivera', action: 'Deployed security fix and verified audit trail', timestamp: 'Yesterday' },
      ],
      comments: [],
      version: 4,
    },
  ],
  'board-01': [
    {
      id: 'item-01-1',
      board_id: 'board-01',
      group_id: 'grp-01-progress',
      title: 'Finalize UX specifications for 3-step onboarding wizard',
      status: 'In Review',
      status_color: '#8b5cf6',
      priority: 'high',
      due_date: 'Tomorrow',
      assignee: {
        id: 'usr-demo-001',
        name: 'Alex Rivera',
        avatar: DEMO_USER.avatar_url!,
      },
      tags: ['UX Design', 'Specs', 'Growth'],
      description: 'Document user flows, drop-off mitigation mechanisms, and celebratory confetti triggers for the new team onboarding funnel.',
      activities: [
        { id: 'act-1', author_name: 'Alex Rivera', action: 'Created task and drafted wireframes', timestamp: 'Yesterday, 4:15 PM' },
        { id: 'act-2', author_name: 'Sarah Jenkins', action: 'Reviewed interaction copy and step validation', timestamp: '2 hours ago' },
      ],
      comments: [
        {
          id: 'comm-1',
          author_name: 'Sarah Jenkins',
          author_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
          content: 'The 3-step progressive profiling is huge for decreasing signup bounce. Ensure the bulk invite step remains optional!',
          timestamp: '3 hours ago',
          reactions: [{ emoji: '👍', count: 3, users: ['Alex Rivera', 'Taylor Chen', 'Marcus Vance'] }],
        },
      ],
    },
    {
      id: 'item-01-2',
      board_id: 'board-01',
      group_id: 'grp-01-todo',
      title: 'Design token architecture for multi-theme support (Dark & Light)',
      status: 'Working on it',
      status_color: '#f59e0b',
      priority: 'urgent',
      due_date: 'Sep 12, 2026',
      assignee: {
        id: 'usr-002',
        name: 'Taylor Chen',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      },
      tags: ['Design System', 'CSS Variables', 'Tokens'],
      description: 'Establish 3-tier CSS variables architecture ensuring WCAG 2.2 AA compliance across dark canvas and light modes.',
      activities: [
        { id: 'act-3', author_name: 'Taylor Chen', action: 'Drafted color tokens in globals.css', timestamp: '5 hours ago' },
      ],
      comments: [],
    },
    {
      id: 'item-01-3',
      board_id: 'board-01',
      group_id: 'grp-01-done',
      title: 'Architect PostgreSQL RLS policies for multi-tenant workspace isolation',
      status: 'Done',
      status_color: '#10b981',
      priority: 'urgent',
      due_date: 'Sep 05, 2026',
      assignee: {
        id: 'usr-demo-001',
        name: 'Alex Rivera',
        avatar: DEMO_USER.avatar_url!,
      },
      tags: ['Backend', 'Security', 'Postgres'],
      description: 'Implemented row-level security for workspaces, members, and invites with automated user creation triggers.',
      activities: [
        { id: 'act-4', author_name: 'Alex Rivera', action: 'Committed migration 20260908000001_month1_foundation.sql', timestamp: 'Sep 05' },
      ],
      comments: [
        {
          id: 'comm-2',
          author_name: 'Marcus Vance',
          author_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
          content: 'Passed security audit for enterprise compliance. Great work!',
          timestamp: 'Sep 06',
          reactions: [{ emoji: '🚀', count: 4, users: ['Alex Rivera', 'Taylor Chen', 'Sarah Jenkins', 'Marcus Vance'] }],
        },
      ],
    },
    {
      id: 'item-01-4',
      board_id: 'board-01',
      group_id: 'grp-01-todo',
      title: 'Kanban view drag-and-drop state persistence',
      status: 'Pending',
      status_color: '#64748b',
      priority: 'medium',
      due_date: 'Sep 18, 2026',
      assignee: {
        id: 'usr-002',
        name: 'Taylor Chen',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      },
      tags: ['Frontend', 'Kanban', 'Views'],
      description: 'Smooth card dragging between status columns with optimistic updates and rollback on network drop.',
      activities: [],
      comments: [],
    },
    {
      id: 'item-01-5',
      board_id: 'board-01',
      group_id: 'grp-01-progress',
      title: 'Keyboard shortcut navigation system (? cheat sheet & roving tabindex)',
      status: 'Working on it',
      status_color: '#f59e0b',
      priority: 'high',
      due_date: 'Sep 14, 2026',
      assignee: {
        id: 'usr-demo-001',
        name: 'Alex Rivera',
        avatar: DEMO_USER.avatar_url!,
      },
      tags: ['Accessibility', 'UX', 'Keyboard'],
      description: 'Support arrow key navigation, ? for shortcut map, and rapid cell editing shortcuts.',
      activities: [],
      comments: [],
    },
    {
      id: 'item-01-6',
      board_id: 'board-01',
      group_id: 'grp-01-done',
      title: 'Unified App Shell with collapsible sidebar and ⌘K Command Palette',
      status: 'Done',
      status_color: '#10b981',
      priority: 'urgent',
      due_date: 'Sep 07, 2026',
      assignee: {
        id: 'usr-demo-001',
        name: 'Alex Rivera',
        avatar: DEMO_USER.avatar_url!,
      },
      tags: ['Navigation', 'Shell', 'CommandPalette'],
      description: 'Fast responsive shell with fuzzy search across boards, workspaces, and actions.',
      activities: [],
      comments: [],
    },
  ],
  'board-02': [
    {
      id: 'item-02-1',
      board_id: 'board-02',
      group_id: 'grp-02-progress',
      title: 'Live WebSocket subscription channel for cell update broadcasts',
      status: 'Working on it',
      status_color: '#f59e0b',
      priority: 'urgent',
      due_date: 'Today, 5:00 PM',
      assignee: {
        id: 'usr-demo-001',
        name: 'Alex Rivera',
        avatar: DEMO_USER.avatar_url!,
      },
      tags: ['WebSockets', 'Realtime', 'Supabase'],
      description: 'Broadcast cell-level diffs with user presence indicators to prevent collision overwrites.',
      activities: [],
      comments: [],
    },
    {
      id: 'item-02-2',
      board_id: 'board-02',
      group_id: 'grp-02-todo',
      title: 'Non-intrusive cell locking banner (Alex is editing...)',
      status: 'Pending',
      status_color: '#64748b',
      priority: 'medium',
      due_date: 'Sep 20, 2026',
      assignee: {
        id: 'usr-002',
        name: 'Taylor Chen',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      },
      tags: ['Collaboration', 'UI', 'Locking'],
      description: 'Display 1.5px colored border in editor avatar color to avoid concurrent write confusion.',
      activities: [],
      comments: [],
    },
  ],
};

export const INITIAL_MY_WORK_ITEMS: MyWorkItem[] = [
  {
    id: 'item-01-1',
    board_id: 'board-01',
    board_name: 'Q3 Product Roadmap',
    workspace_id: 'ws-acme-core',
    title: 'Finalize UX specifications for 3-step onboarding wizard',
    status: 'In Review',
    status_color: '#8b5cf6',
    priority: 'high',
    due_date: 'Tomorrow',
    assignee_id: 'usr-demo-001',
    is_overdue: false,
  },
  {
    id: 'item-02-1',
    board_id: 'board-02',
    board_name: 'Sprint 24 — Realtime Engine',
    workspace_id: 'ws-acme-core',
    title: 'Configure Supabase RLS policies for multi-tenant workspace isolation',
    status: 'Working on it',
    status_color: '#f59e0b',
    priority: 'urgent',
    due_date: 'Today, 5:00 PM',
    assignee_id: 'usr-demo-001',
    is_overdue: false,
  },
  {
    id: 'item-01-5',
    board_id: 'board-01',
    board_name: 'Q3 Product Roadmap',
    workspace_id: 'ws-acme-core',
    title: 'Design keyboard shortcut palette (⌘K) with fuzzy board search',
    status: 'Done',
    status_color: '#10b981',
    priority: 'medium',
    due_date: 'Yesterday',
    assignee_id: 'usr-demo-001',
    is_overdue: false,
  },
  {
    id: 'item-01-2',
    board_id: 'board-01',
    board_name: 'Q3 Product Roadmap',
    workspace_id: 'ws-acme-core',
    title: 'Design token architecture for multi-theme support (Dark & Light)',
    status: 'Working on it',
    status_color: '#f59e0b',
    priority: 'urgent',
    due_date: 'Sep 12, 2026',
    assignee_id: 'usr-demo-001',
    is_overdue: false,
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-01',
    title: 'Taylor Chen mentioned you',
    description: 'in "Sprint 24 — Realtime Engine": "Take a look at the websocket channel schema"',
    timestamp: '12m ago',
    unread: true,
    type: 'mention',
  },
  {
    id: 'notif-02',
    title: 'Assigned to new task',
    description: 'You were assigned to "Configure Supabase RLS policies for multi-tenant isolation"',
    timestamp: '45m ago',
    unread: true,
    type: 'assignment',
  },
  {
    id: 'notif-03',
    title: 'Workspace Invite Accepted',
    description: 'Sarah Jenkins accepted your invitation to join Acme Product Lab',
    timestamp: '2h ago',
    unread: false,
    type: 'invite',
  },
  {
    id: 'notif-04',
    title: 'Security Notice',
    description: 'New session authenticated from Chrome 134 on Windows 11',
    timestamp: '1d ago',
    unread: false,
    type: 'system',
  },
];

export const INITIAL_GITHUB_COMMITS: GitHubCommit[] = [
  {
    id: 'f83a1b2',
    full_sha: 'f83a1b293d84a51e607e47a98b46231908d17a32',
    repo: 'happytf/work-os-core',
    branch: 'main',
    message: 'fix(export): stream CSV chunked response to resolve gateway 504 (#TK-1042)',
    url: 'https://github.com/happytf/work-os-core/commit/f83a1b2',
    timestamp: '4 mins ago',
    author: {
      name: 'Alex Rivera',
      username: 'alexrivera',
      avatar: DEMO_USER.avatar_url!,
    },
    linked_ticket_number: 'TK-1042',
  },
  {
    id: 'e49c71a',
    full_sha: 'e49c71a179b5c2d3e09886a0b9432e12817bf401',
    repo: 'happytf/work-os-core',
    branch: 'feat/occ-claiming',
    message: 'feat(tickets): add optimistic locking to task claim endpoint (#TK-1044)',
    url: 'https://github.com/happytf/work-os-core/commit/e49c71a',
    timestamp: '18 mins ago',
    author: {
      name: 'Taylor Chen',
      username: 'taylorchen',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    },
    linked_ticket_number: 'TK-1044',
  },
  {
    id: '3b18df0',
    full_sha: '3b18df092b34a58c09a87612f094e21a89bf1112',
    repo: 'happytf/work-os-core',
    branch: 'fix/rls-isolation',
    message: 'perf(db): add partial index on ticket_number and board_id for fast lookup',
    url: 'https://github.com/happytf/work-os-core/commit/3b18df0',
    timestamp: '1 hour ago',
    author: {
      name: 'Jordan Lee',
      username: 'jordanlee',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    },
  },
  {
    id: '9a02ce4',
    full_sha: '9a02ce428b49e01f28b7462198d017b2938a1928',
    repo: 'happytf/work-os-core',
    branch: 'main',
    message: 'chore(deps): bump @supabase/supabase-js from 2.48.0 to 2.49.1',
    url: 'https://github.com/happytf/work-os-core/commit/9a02ce4',
    timestamp: '3 hours ago',
    author: {
      name: 'Sarah Jenkins',
      username: 'sarahjenkins',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    },
  },
];
